### ISSUE TITLE
openshift-ansible postsubmits are broken

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#1392]
All of them are failing with the following error:
```
########## STARTING STAGE: ENSURE BUILT VERSION OF ORIGIN IS INSTALLED ##########
+ [[ -s /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83
++ export PATH=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config
++ mktemp
+ script=/tmp/tmp.GUI1oNoUnW
+ cat
+ chmod +x /tmp/tmp.GUI1oNoUnW
+ scp -F /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.GUI1oNoUnW openshiftdevel:/tmp/tmp.GUI1oNoUnW
+ ssh -F /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "timeout 600 /tmp/tmp.GUI1oNoUnW"'
+ cd /data/src/github.com/openshift/aos-cd-jobs
++ cat ./ORIGIN_TAG
+ docker_image_tag=v3.10
+ docker_repository=openshift/origin
+ docker inspect openshift/origin:v3.10
[]
Error: No such object: openshift/origin:v3.10
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: ENSURE BUILT VERSION OF ORIGIN IS INSTALLED [00h 00m 00s] ##########
```
@sdodson @smarterclayton

**Comment by kargakis** [comment]
To be fair I just see it in 

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update_containerized/395/

and 

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_containerized/395/

Other version related failures in:

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update_system_containers/395/

**Comment by smarterclayton** [comment]
Related to Jenkins upgrade?

On May 21, 2018, at 6:34 AM, Michalis Kargakis <notifications@github.com>
wrote:

All of them are failing with the following error:

########## STARTING STAGE: ENSURE BUILT VERSION OF ORIGIN IS INSTALLED
##########
+ [[ -s /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/activate
]]
+ source /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83
++ export PATH=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/7a5c5e83c372ad2e6b3b64b3efa16fe2cb37ef83/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config
++ mktemp
+ script=/tmp/tmp.GUI1oNoUnW
+ cat
+ chmod +x /tmp/tmp.GUI1oNoUnW
+ scp -F /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config/origin-ci-tool/inventory/.ssh_config
/tmp/tmp.GUI1oNoUnW openshiftdevel:/tmp/tmp.GUI1oNoUnW
+ ssh -F /var/lib/jenkins/jobs/test_branch_origin_extended_conformance_install_containerized/workspace/.config/origin-ci-tool/inventory/.ssh_config
-t openshiftdevel 'bash -l -c "timeout 600 /tmp/tmp.GUI1oNoUnW"'
+ cd /data/src/github.com/openshift/aos-cd-jobs
++ cat ./ORIGIN_TAG
+ docker_image_tag=v3.10
+ docker_repository=openshift/origin
+ docker inspect openshift/origin:v3.10
[]
Error: No such object: openshift/origin:v3.10
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: ENSURE BUILT VERSION OF ORIGIN IS
INSTALLED [00h 00m 00s] ##########

@sdodson <https://github.com/sdodson> @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/aos-cd-jobs/issues/1392>, or mute the thread

**Comment by sdodson** [comment]
Not sure and I'm not familiar with that stage of the CI jobs. We should figure out the problem but then also consider disabling all containerized and system container jobs on origin master as it's not a supported deployment model in 3.10.

**Comment by smarterclayton** [comment]
Those should already all be disabled on master.  I think those are the
older branch jobs.

**Comment by kargakis** [comment]
Seeing these failures in openshift/openshift-ansible#master

https://deck-ci.svc.ci.openshift.org/?repo=openshift%2Fopenshift-ansible&type=postsubmit
